name: Build iOS
on:
  workflow_dispatch:
  workflow_call:

env:
  GODOT_BASE_BRANCH: main

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - precision: single
            arch: arm64
            ios_precision_extension:
          - precision: double
            arch: arm64
            ios_precision_extension: .double
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build
        uses: ./.github/actions/scons-build
        with:
          platform: ios
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.precision }}
          build-target-type: template_release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Godot_Whisper-ios-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/libgodot_whisper.ios.template_release${{ matrix.ios_precision_extension }}.arm64.framework/**
          if-no-files-found: error
