name: Build Web
on:
  workflow_dispatch:
  workflow_call:

env:
  GODOT_BASE_BRANCH: main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # CPU-only (emscripten 4.0.11)
          - precision: single
            arch: wasm32
            gpu: cpu
          - precision: double
            arch: wasm32
            gpu: cpu
          # WebGPU (requires emscripten 4.0+). Disabled until Godot supports emscripted 4.0+
          #- precision: single
          #  arch: wasm32
          #  gpu: webgpu
          #- precision: double
          #  arch: wasm32
          #  gpu: webgpu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: 🔗 GDExtension Build (CPU-only)
        if: ${{ matrix.gpu == 'cpu' }}
        uses: ./.github/actions/scons-build
        with:
          platform: web
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.precision }}
          build-target-type: template_release
          em-version: "4.0.11"

      - name: 🔗 GDExtension Build (WebGPU)
        if: ${{ matrix.gpu == 'webgpu' }}
        uses: ./.github/actions/scons-build
        env:
          WEBGPU: "yes"
        with:
          platform: web
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.precision }}
          build-target-type: template_release
          em-version: "4.0.11"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Godot_Whisper-web-${{ matrix.gpu }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/*.wasm
          if-no-files-found: error
