name: Build Windows
on:
  workflow_dispatch:
  workflow_call:

env:
  GODOT_BASE_BRANCH: main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - precision: single
            arch: x86_64
          - precision: double
            arch: x86_64
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.4
        with:
          vulkan_version: 1.3.296.0
          install_runtime: false

      - name: 🔗 GDExtension Build
        uses: ./.github/actions/scons-build
        env:
          VULKAN: "yes"
        with:
          platform: windows
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.precision }}
          build-target-type: template_release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Godot_Whisper-windows-${{ matrix.arch }}-${{ matrix.precision }}
          path: |
            ${{ github.workspace }}/bin/**/*.dll
            ${{ github.workspace }}/bin/samples/**
            ${{ github.workspace }}/bin/addons/godot_whisper/audio_stream_to_text.gd
            ${{ github.workspace }}/bin/addons/godot_whisper/capture_stream_to_text.gd
            ${{ github.workspace }}/bin/addons/godot_whisper/godot_whisper.gdextension
            ${{ github.workspace }}/bin/addons/godot_whisper/label_transcribe.gd
            ${{ github.workspace }}/bin/addons/godot_whisper/model_downloader.gd
            ${{ github.workspace }}/bin/addons/godot_whisper/plugin.cfg
            ${{ github.workspace }}/bin/addons/godot_whisper/whisper_dock.gd
            ${{ github.workspace }}/bin/addons/godot_whisper/whisper_dock.tscn
            ${{ github.workspace }}/bin/addons/godot_whisper/models/gglm-tiny.en.bin
          if-no-files-found: error
